"""add port and password history

Revision ID: 26147aaf44cc
Revises: 46f71f165b02
Create Date: 2026-07-31 22:39:52.374109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26147aaf44cc'
down_revision = '46f71f165b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['proxy_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proxy_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('port', sa.Integer(), nullable=True))

    # assign default ports to existing rows
    op.execute("UPDATE proxy_users SET port = id + 10800 WHERE port IS NULL")

    with op.batch_alter_table('proxy_users', schema=None) as batch_op:
        batch_op.alter_column('port', nullable=False)
        batch_op.create_unique_constraint('uq_proxy_users_port', ['port'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proxy_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('port')

    op.drop_table('password_history')
    # ### end Alembic commands ###
