"""remove unique username constraint

Revision ID: 6cd0cf1b5953
Revises: 26147aaf44cc
Create Date: 2026-07-31 22:54:56.678415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd0cf1b5953'
down_revision = '26147aaf44cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proxy_users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('proxy_users_username_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proxy_users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('proxy_users_username_key'), ['username'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
